version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITRD_ROOT_USERNAME: root
      MONGO_INITRD_ROOT_PASSWORD: examplepassword
      MONGO_INITRD_DATABASE: MONGO_TEST